export type PlantCategory = 'Perennials' | 'Grasses' | 'Shrubs' | 'Groundcovers' | 'Bulbs' | 'Climbers' | 'Trees';

export interface PlantCatalogItem {
  name: string;
  nameDutch: string;
  latinName: string;
  description: string;
  category: PlantCategory;
  emoji: string;
  bloomSeason?: string;
  sunRequirement?: string;
  waterNeeds?: string;
}

function plant(
  name: string,
  nameDutch: string,
  latinName: string,
  description: string,
  category: PlantCategory,
  emoji: string,
  bloomSeason?: string,
  sunRequirement?: string,
  waterNeeds?: string,
): PlantCatalogItem {
  return { name, nameDutch, latinName, description, category, emoji, bloomSeason, sunRequirement, waterNeeds };
}

export const PLANT_CATALOG: PlantCatalogItem[] = [
  // ── Perennials ──
  plant('Lavender', 'Lavendel', 'Lavandula angustifolia', 'Fragrant silver-purple spikes. Drought tolerant, pollinator magnet.', 'Perennials', '🌸', 'Jun–Aug', 'Full Sun', 'Low'),
  plant('Catmint', 'Kattenkruid', 'Nepeta faassenii', 'Soft blue-violet flowers over silvery foliage. Long blooming.', 'Perennials', '🌸', 'May–Sep', 'Full Sun', 'Low'),
  plant('Salvia', 'Salie', 'Salvia nemorosa', 'Upright violet spikes loved by bees. Repeat bloomer.', 'Perennials', '🌸', 'Jun–Aug', 'Full Sun', 'Low'),
  plant('Echinacea', 'Zonnehoed', 'Echinacea purpurea', 'Bold pink daisy-like flowers. Bird-attracting seed heads in winter.', 'Perennials', '🌸', 'Jul–Sep', 'Full Sun', 'Low'),
  plant('Rudbeckia', 'Zonnebloem', 'Rudbeckia fulgida', 'Bright yellow daisies with dark centers. Late summer color.', 'Perennials', '🌻', 'Jul–Oct', 'Full Sun', 'Average'),
  plant('Astilbe', 'Pluimspirea', 'Astilbe × arendsii', 'Feathery plumes in pink, red, or white. Loves moisture and shade.', 'Perennials', '🌸', 'Jun–Aug', 'Part Shade', 'High'),
  plant('Hosta', 'Hartlelie', 'Hosta spp.', 'Bold architectural foliage in blue, green, or gold. Shade star.', 'Perennials', '🍃', 'Jun–Aug', 'Shade', 'Average'),
  plant('Heuchera', 'Purperklokje', 'Heuchera spp.', 'Colorful foliage in burgundy, lime, or caramel. Bell-shaped flowers.', 'Perennials', '🍃', 'May–Jul', 'Part Shade', 'Average'),
  plant('Hardy Geranium', 'Ooievaarsbek', 'Geranium × magnificum', 'Cheerful five-petaled flowers. Self-seeding ground filler.', 'Perennials', '🌸', 'May–Jul', 'Full Sun / Part Shade', 'Average'),
  plant('Yarrow', 'Duizendblad', 'Achillea millefolium', 'Flat-topped flower clusters in white, yellow, or pink. Very tough.', 'Perennials', '🌼', 'Jun–Aug', 'Full Sun', 'Low'),
  plant('Phlox', 'Vlambloem', 'Phlox paniculata', 'Fragrant domed flower heads in pink, white, or purple.', 'Perennials', '🌸', 'Jul–Sep', 'Full Sun', 'Average'),
  plant('Daylily', 'Daglelie', 'Hemerocallis spp.', 'Trumpet flowers that open for a single day. Very adaptable.', 'Perennials', '🌺', 'Jun–Aug', 'Full Sun', 'Low'),
  plant('Delphinium', 'Ridderspoor', 'Delphinium elatum', 'Tall dramatic spikes in blue, purple, or white. Classic cottage plant.', 'Perennials', '🌸', 'Jun–Jul', 'Full Sun', 'Average'),
  plant('Foxglove', 'Vingerhoedskruid', 'Digitalis purpurea', 'Tall spires of tubular flowers. Self-seeds freely.', 'Perennials', '🌸', 'Jun–Jul', 'Part Shade', 'Average'),
  plant('Agapanthus', 'Afrikaanse blauwe lelie', 'Agapanthus africanus', 'Striking blue or white globes on long stems. Architectural.', 'Perennials', '🌸', 'Jul–Aug', 'Full Sun', 'Low'),
  plant('Crocosmia', 'Montbretia', 'Crocosmia × crocosmiiflora', 'Arching sprays of fiery orange-red flowers. Hummingbird favorite.', 'Perennials', '🌺', 'Jul–Aug', 'Full Sun', 'Average'),
  plant('Iris', 'Iris', 'Iris germanica', 'Stunning bearded or Siberian blooms in every color.', 'Perennials', '🌸', 'May–Jun', 'Full Sun', 'Low'),
  plant('Aquilegia', 'Akelei', 'Aquilegia vulgaris', 'Spurred nodding blooms in intricate two-tone colors.', 'Perennials', '🌸', 'May–Jun', 'Part Shade', 'Average'),
  plant('Bergenia', 'Schoenlappersplant', 'Bergenia cordifolia', 'Bold glossy leaves, pink spring flowers. Winter red foliage.', 'Perennials', '🌸', 'Mar–May', 'Part Shade', 'Average'),
  plant('Bleeding Heart', 'Gebroken hartje', 'Lamprocapnos spectabilis', 'Dangling heart-shaped flowers on arching stems.', 'Perennials', '🌸', 'Apr–May', 'Part Shade', 'Average'),
  plant('Campanula', 'Klokjesbloem', 'Campanula persicifolia', 'Bell-shaped flowers in blue or white. Elegant and easy.', 'Perennials', '🌸', 'Jun–Jul', 'Full Sun / Part Shade', 'Average'),
  plant('Coreopsis', 'Meisjesogen', 'Coreopsis grandiflora', 'Bright yellow daisy flowers all summer. Very long blooming.', 'Perennials', '🌻', 'Jun–Sep', 'Full Sun', 'Low'),
  plant('Gaillardia', 'Kokardebloem', 'Gaillardia × grandiflora', 'Vivid red-yellow bicolor daisies. Extremely long blooming.', 'Perennials', '🌺', 'Jun–Oct', 'Full Sun', 'Low'),
  plant('Hellebore', 'Nieskruid', 'Helleborus × hybridus', 'Nodding flowers in winter and spring. Shade tolerant.', 'Perennials', '🌸', 'Jan–Apr', 'Shade', 'Average'),
  plant('Kniphofia', 'Vuurpijl', 'Kniphofia uvaria', 'Bold torchlike flowers in red, orange, and yellow.', 'Perennials', '🌺', 'Jul–Sep', 'Full Sun', 'Low'),
  plant('Liatris', 'Slangenwortel', 'Liatris spicata', 'Fluffy purple spikes that open top-down. Pollinator magnet.', 'Perennials', '🌸', 'Jul–Sep', 'Full Sun', 'Low'),
  plant('Monarda', 'Bergamot', 'Monarda didyma', 'Shaggy tubular flowers in red, pink, or white. Fragrant.', 'Perennials', '🌺', 'Jul–Aug', 'Full Sun', 'Average'),
  plant('Peony', 'Pioenroos', 'Paeonia lactiflora', 'Luxurious fragrant blooms in white, pink, or red.', 'Perennials', '🌸', 'May–Jun', 'Full Sun', 'Average'),
  plant('Oriental Poppy', 'Oosterse klaproos', 'Papaver orientale', 'Huge crepe-paper petals in vivid orange, red, or pink.', 'Perennials', '🌺', 'May–Jun', 'Full Sun', 'Low'),
  plant('Scabiosa', 'Duifkruid', 'Scabiosa caucasica', 'Delicate pincushion flowers in lavender-blue. Butterfly magnet.', 'Perennials', '🌸', 'Jun–Sep', 'Full Sun', 'Low'),
  plant('Sedum (Stonecrop)', 'Vetkruid', 'Hylotelephium spectabile', 'Succulent foliage and flat pink flower heads. Autumn interest.', 'Perennials', '🌸', 'Aug–Oct', 'Full Sun', 'Low'),
  plant('Verbena bonariensis', 'IJzerhard', 'Verbena bonariensis', 'Airy tall purple flower clusters. See-through plant.', 'Perennials', '🌸', 'Jul–Oct', 'Full Sun', 'Low'),
  plant('Thalictrum', 'Ruit', 'Thalictrum aquilegiifolium', 'Fluffy lavender cloud of tiny flowers. Delicate foliage.', 'Perennials', '🌸', 'Jun–Jul', 'Part Shade', 'Average'),
  plant('Veronicastrum', 'Virginische ereprijs', 'Veronicastrum virginicum', 'Tall slender candles of tiny flowers. Architectural.', 'Perennials', '🌸', 'Jul–Sep', 'Full Sun', 'Average'),
  plant('Acanthus', 'Akant', 'Acanthus mollis', 'Dramatic large lobed foliage and tall white-purple spikes.', 'Perennials', '🌸', 'Jun–Jul', 'Part Shade', 'Low'),
  plant('Hollyhock', 'Stokroos', 'Alcea rosea', 'Tall cottage spires with cup-shaped flowers in many colors.', 'Perennials', '🌺', 'Jun–Aug', 'Full Sun', 'Average'),
  plant('Aster', 'Aster', 'Aster × frikartii', 'Late-season daisy flowers in blue, purple, pink, or white.', 'Perennials', '🌸', 'Aug–Oct', 'Full Sun', 'Average'),
  plant('Astrantia', 'Zeeuws knoopje', 'Astrantia major', 'Intricate pincushion flowers with star-like bracts. Cottage charm.', 'Perennials', '🌸', 'Jun–Aug', 'Part Shade', 'Average'),
  plant('Persicaria', 'Duizendknoop', 'Persicaria amplexicaulis', 'Long-lasting bottle-brush spikes of red or pink. Very floriferous.', 'Perennials', '🌸', 'Jun–Oct', 'Full Sun', 'Average'),
  plant('Stachys', 'Ezelsoor', 'Stachys byzantina', 'Soft woolly silver-grey leaves. Pink summer flowers.', 'Perennials', '🌿', 'Jun–Aug', 'Full Sun', 'Low'),
  plant('Euphorbia', 'Wolfsmelk', 'Euphorbia × martini', 'Architectural spurge with lime-yellow bracts. Long-lasting.', 'Perennials', '🌿', 'Mar–Jun', 'Full Sun', 'Low'),
  plant('Gaura', 'Prachtkaars', 'Gaura lindheimeri', 'Airy wands with butterfly-like white-pink flowers. Long blooming.', 'Perennials', '🌸', 'Jun–Oct', 'Full Sun', 'Low'),
  plant('Helenium', 'Zonnekruid', 'Helenium autumnale', 'Warm-toned daisy flowers in bronze, orange, yellow. Late summer.', 'Perennials', '🌻', 'Aug–Oct', 'Full Sun', 'Average'),
  plant('Ligularia', 'Goudvink', 'Ligularia dentata', 'Bold round leaves and vivid orange daisy flowers. Loves moisture.', 'Perennials', '🌻', 'Jul–Aug', 'Part Shade', 'High'),
  plant('Polemonium', 'Jacobsladder', 'Polemonium caeruleum', 'Ladder-like compound leaves, blue bell flowers. Cottage classic.', 'Perennials', '🌸', 'May–Jul', 'Part Shade', 'Average'),
  plant('Pulmonaria', 'Longkruid', 'Pulmonaria officinalis', 'Spotted silver foliage, pink-to-blue spring flowers. Shade.', 'Perennials', '🌸', 'Mar–Apr', 'Shade', 'Average'),
  plant('Tiarella', 'Schuimbloem', 'Tiarella cordifolia', 'Lobed leaves with beautiful markings. Frothy white flowers.', 'Perennials', '🌸', 'Apr–Jun', 'Shade', 'Average'),
  plant('Erigeron', 'Fijnstraal', 'Erigeron karvinskianus', 'Masses of tiny white-pink daisy flowers. Spreads freely.', 'Perennials', '🌸', 'Jun–Oct', 'Full Sun', 'Low'),
  plant('Lysimachia', 'Wederik', 'Lysimachia punctata', 'Whorls of yellow flowers on upright stems. Colonizing.', 'Perennials', '🌼', 'Jun–Aug', 'Full Sun / Part Shade', 'Average'),
  plant('Oenothera', 'Teunisbloem', 'Oenothera speciosa', 'Large cup-shaped flowers that open in evening.', 'Perennials', '🌸', 'Jun–Aug', 'Full Sun', 'Low'),
  plant('Verbascum', 'Toorts', 'Verbascum chaixii', 'Tall architectural spires of saucer flowers. Drought tolerant.', 'Perennials', '🌼', 'Jun–Aug', 'Full Sun', 'Low'),
  plant('Alstroemeria', 'Incalelie', 'Alstroemeria spp.', 'Long-lasting exotic trumpet flowers in vibrant mixed tones.', 'Perennials', '🌺', 'Jun–Sep', 'Full Sun', 'Average'),
  plant('Platycodon', 'Ballonklokje', 'Platycodon grandiflorus', 'Balloon-like buds open to star-shaped blue flowers.', 'Perennials', '🌸', 'Jul–Aug', 'Full Sun', 'Average'),
  plant('Veronica', 'Ereprijs', 'Veronica spicata', 'Upright spikes of tiny intense blue or white flowers.', 'Perennials', '🌸', 'Jun–Aug', 'Full Sun', 'Average'),
  plant('Penstemon', 'Schildpadbloem', 'Penstemon digitalis', 'Tubular flowers in pink, red, or purple. Hummingbird plant.', 'Perennials', '🌸', 'Jun–Aug', 'Full Sun', 'Average'),
  plant('Lychnis', 'Lichtnelk', 'Lychnis coronaria', 'Vivid magenta flowers over silver-grey woolly foliage.', 'Perennials', '🌺', 'Jun–Aug', 'Full Sun', 'Low'),
  plant('Waldsteinia', 'Gouden aardbei', 'Waldsteinia ternata', 'Cheerful yellow flowers over glossy lobed foliage. Ground cover.', 'Perennials', '🌼', 'Apr–May', 'Part Shade', 'Low'),

  // ── Grasses ──
  plant('Miscanthus', 'Chinagrijs', 'Miscanthus sinensis', 'Tall elegant grass with feathery plumes. Stunning autumn color.', 'Grasses', '🌾', 'Sep–Nov', 'Full Sun', 'Average'),
  plant('Feather Reed Grass', 'Struisriet', 'Calamagrostis × acutiflora', 'Upright architectural grass with feathery spikes. Four-season.', 'Grasses', '🌾', 'Jun–Oct', 'Full Sun', 'Average'),
  plant('Fountain Grass', 'Lampenpoetsergras', 'Pennisetum alopecuroides', 'Graceful arching grass with fuzzy bottlebrush plumes.', 'Grasses', '🌾', 'Aug–Oct', 'Full Sun', 'Average'),
  plant('Mexican Feather Grass', 'Parelgrijs', 'Nassella tenuissima', 'Silky hair-fine grass that shimmers in the wind.', 'Grasses', '🌾', 'Jun–Sep', 'Full Sun', 'Low'),
  plant('Purple Moor Grass', 'Pijpenstrootje', 'Molinia caerulea', 'Elegant transparent grass. Golden amber autumn color.', 'Grasses', '🌾', 'Aug–Oct', 'Full Sun / Part Shade', 'Average'),
  plant('Tufted Hair Grass', 'Ruwe smele', 'Deschampsia cespitosa', 'Mist-like transparent green flower clouds over dark base.', 'Grasses', '🌾', 'Jun–Aug', 'Part Shade', 'Average'),
  plant('Carex', 'Zegge', 'Carex morrowii', 'Evergreen sedge with arching leaves. Tolerates shade and moisture.', 'Grasses', '🌾', 'Apr–May', 'Part Shade', 'Average'),
  plant('Blue Fescue', 'Schapengras', 'Festuca glauca', 'Compact tufts of striking steel-blue foliage.', 'Grasses', '🌾', 'Jun', 'Full Sun', 'Low'),
  plant('Japanese Forest Grass', 'Japans berggrijs', 'Hakonechloa macra', 'Cascading gold-green foliage. Glows in shade.', 'Grasses', '🌾', 'Aug–Sep', 'Part Shade', 'Average'),
  plant('Switch Grass', 'Vingergras', 'Panicum virgatum', 'Airy fine-textured grass. Red-orange autumn color.', 'Grasses', '🌾', 'Aug–Oct', 'Full Sun', 'Low'),
  plant('Quaking Grass', 'Trilgras', 'Briza maxima', 'Dangling heart-shaped spikelets tremble in breeze.', 'Grasses', '🌾', 'Jun–Jul', 'Full Sun', 'Low'),
  plant('Japanese Blood Grass', 'Japans bloedgras', 'Imperata cylindrica', 'Striking red-tipped blades that glow when backlit.', 'Grasses', '🌾', 'Summer', 'Full Sun', 'Average'),
  plant('Wood Rush', 'Veldbies', 'Luzula sylvatica', 'Evergreen spreading grass-like plant for dry shade.', 'Grasses', '🌾', 'Apr–May', 'Shade', 'Low'),
  plant('Ribbon Grass', 'Rietgras', 'Phalaris arundinacea', 'Green-white striped foliage. Vigorous colonizer.', 'Grasses', '🌾', 'Jun', 'Full Sun', 'Average'),
  plant('Blue Oat Grass', 'Blauw havergras', 'Helictotrichon sempervirens', 'Steel-blue fine-textured tufts. Dramatic form.', 'Grasses', '🌾', 'Jun–Jul', 'Full Sun', 'Low'),
  plant('Pampas Grass', 'Pampasgras', 'Cortaderia selloana', 'Large ornamental grass with huge silvery plumes. Bold statement.', 'Grasses', '🌾', 'Sep–Nov', 'Full Sun', 'Low'),
  plant('Big Bluestem', 'Prairiegrijs', 'Andropogon gerardii', 'Tall prairie grass with bluish stems. Copper autumn color.', 'Grasses', '🌾', 'Aug–Sep', 'Full Sun', 'Low'),
  plant('Prairie Dropseed', 'Grasachtigen', 'Sporobolus heterolepis', 'Fine-textured grass with fragrant fall flowers.', 'Grasses', '🌾', 'Aug–Sep', 'Full Sun', 'Low'),
  plant('Silver Spear Grass', 'Zilverspeer', 'Stipa gigantea', 'Tall golden-oat heads on long stems. Statuesque structure.', 'Grasses', '🌾', 'Jun–Aug', 'Full Sun', 'Low'),
  plant('Sesleria', 'Sesleria', 'Sesleria autumnalis', 'Compact grass with attractive autumn flower heads. Robust.', 'Grasses', '🌾', 'Sep–Oct', 'Full Sun / Part Shade', 'Low'),

  // ── Shrubs ──
  plant('Hydrangea', 'Hortensia', 'Hydrangea macrophylla', 'Spectacular mophead or lacecap flowers. Long season color.', 'Shrubs', '🌸', 'Jul–Sep', 'Part Shade', 'High'),
  plant('Panicle Hydrangea', 'Pluimhortensia', 'Hydrangea paniculata', 'Conical white plumes ageing to pink. More sun tolerant.', 'Shrubs', '🌸', 'Jul–Oct', 'Full Sun', 'Average'),
  plant('Annabelle Hydrangea', 'Annabelle hortensia', 'Hydrangea arborescens', 'Giant white snowball flowers. Reliable bloomer.', 'Shrubs', '🌸', 'Jun–Aug', 'Part Shade', 'Average'),
  plant('Climbing Hydrangea', 'Klimhortensia', 'Hydrangea anomala petiolaris', 'Self-clinging climber with white lacecap flowers.', 'Shrubs', '🌸', 'Jun–Jul', 'Part Shade', 'Average'),
  plant('Butterfly Bush', 'Vlinderstruik', 'Buddleja davidii', 'Fragrant arching plumes loved by butterflies. Fast growing.', 'Shrubs', '🌸', 'Jul–Sep', 'Full Sun', 'Low'),
  plant('Elderberry', 'Vlier', 'Sambucus nigra', 'Large creamy flowerheads, then black berries. Purple-leaf forms.', 'Shrubs', '🌿', 'Jun', 'Full Sun / Part Shade', 'Average'),
  plant('Viburnum', 'Viburnum', 'Viburnum × burkwoodii', 'Fragrant white flower clusters, sometimes evergreen.', 'Shrubs', '🌸', 'Apr–May', 'Full Sun / Part Shade', 'Average'),
  plant('Spiraea', 'Spierstruik', 'Spiraea japonica', 'Clouds of tiny flowers in pink or white. Easy and tough.', 'Shrubs', '🌸', 'Jun–Aug', 'Full Sun', 'Average'),
  plant('Mexican Orange', 'Mexicaanse sinaasappel', 'Choisya ternata', 'Evergreen with fragrant white flowers. Star foliage.', 'Shrubs', '🌸', 'Apr–May', 'Full Sun', 'Average'),
  plant('Smoke Bush', 'Pruikenboom', 'Cotinus coggygria', 'Hazy pink-purple smoke puffs over dark purple foliage.', 'Shrubs', '🌸', 'Jun–Jul', 'Full Sun', 'Low'),
  plant('Cornus', 'Kornoelje', 'Cornus alba', 'Brilliant red winter stems. White flowers, white berries.', 'Shrubs', '🌿', 'May', 'Full Sun / Part Shade', 'Average'),
  plant('Forsythia', 'Forsythia', 'Forsythia × intermedia', 'Masses of bright yellow flowers on bare stems in early spring.', 'Shrubs', '🌼', 'Mar–Apr', 'Full Sun', 'Average'),
  plant('Hebe', 'Struikveronica', 'Hebe spp.', 'Evergreen with bottle-brush flowers. Wide color range.', 'Shrubs', '🌿', 'Jun–Oct', 'Full Sun', 'Average'),
  plant('Rose of Sharon', 'Roos van Sharon', 'Hibiscus syriacus', 'Late-season large trumpet flowers in pink, blue, or white.', 'Shrubs', '🌺', 'Aug–Oct', 'Full Sun', 'Average'),
  plant('Hypericum', 'Hertshooi', 'Hypericum calycinum', 'Gold saucer flowers with showy stamens. Semi-evergreen.', 'Shrubs', '🌼', 'Jun–Sep', 'Full Sun / Part Shade', 'Low'),
  plant('Kolkwitzia', 'Schoonheidsstruik', 'Kolkwitzia amabilis', 'Covered in small pink bell flowers in late spring.', 'Shrubs', '🌸', 'May–Jun', 'Full Sun', 'Average'),
  plant('Potentilla', 'Ganzerik', 'Potentilla fruticosa', 'Non-stop single flowers in yellow, pink, or white.', 'Shrubs', '🌼', 'Jun–Oct', 'Full Sun', 'Low'),
  plant('Japanese Maple', 'Japanse esdoorn', 'Acer palmatum', 'Spectacular dissected foliage in green, red, or purple.', 'Shrubs', '🍁', 'Oct', 'Part Shade', 'Average'),
  plant('Mahonia', 'Mahonia', 'Mahonia × media', 'Evergreen with holly-like leaves, yellow winter flowers, blue berries.', 'Shrubs', '🌿', 'Nov–Feb', 'Shade', 'Low'),
  plant('Nandina', 'Hemelse bamboe', 'Nandina domestica', 'Elegant bamboo-like foliage turning fiery in winter.', 'Shrubs', '🌿', 'Jun', 'Full Sun / Part Shade', 'Low'),
  plant('Mock Orange', 'Boerenjasmijn', 'Philadelphus coronarius', 'Intensely fragrant white flowers. Classic cottage shrub.', 'Shrubs', '🌸', 'Jun', 'Full Sun', 'Average'),
  plant('Ninebark', 'Vogelbes', 'Physocarpus opulifolius', 'Attractive exfoliating bark. Dark purple or gold foliage.', 'Shrubs', '🌿', 'Jun', 'Full Sun', 'Average'),
  plant('Weigela', 'Weigela', 'Weigela florida', 'Masses of trumpet flowers in pink or red. Reliable performer.', 'Shrubs', '🌸', 'May–Jun', 'Full Sun', 'Average'),
  plant('Caryopteris', 'Blauwbaard', 'Caryopteris × clandonensis', 'Late-season blue-lavender flowers. Aromatic silver foliage.', 'Shrubs', '🌸', 'Aug–Oct', 'Full Sun', 'Low'),
  plant('Callicarpa', 'Schoonvrucht', 'Callicarpa bodinieri', 'Extraordinary clusters of vivid violet berries in autumn.', 'Shrubs', '🌿', 'Aug (fruit)', 'Full Sun', 'Average'),
  plant('Skimmia', 'Skimmia', 'Skimmia japonica', 'Evergreen with fragrant flowers and long-lasting red berries.', 'Shrubs', '🌿', 'Mar–May', 'Shade', 'Average'),
  plant('Abelia', 'Abelia', 'Abelia × grandiflora', 'Semi-evergreen with arching branches, pink-white flowers.', 'Shrubs', '🌸', 'Jul–Oct', 'Full Sun', 'Average'),
  plant('Fothergilla', 'Fothergilla', 'Fothergilla major', 'Bottlebrush flowers in spring, fiery autumn color.', 'Shrubs', '🌸', 'Apr–May', 'Full Sun / Part Shade', 'Average'),
  plant('Pittosporum', 'Tobira', 'Pittosporum tobira', 'Evergreen with fragrant white flowers. Dense, architectural.', 'Shrubs', '🌿', 'May–Jun', 'Full Sun', 'Average'),
  plant('Ribes', 'Bloedbes', 'Ribes sanguineum', 'Hanging clusters of pink-red flowers before leaves emerge.', 'Shrubs', '🌸', 'Mar–Apr', 'Full Sun', 'Average'),
  plant('Deutzia', 'Deutzia', 'Deutzia × elegantissima', 'Arching stems covered in starry flowers in late spring.', 'Shrubs', '🌸', 'May–Jun', 'Full Sun', 'Average'),
  plant('Osmanthus', 'Schijnhulst', 'Osmanthus × burkwoodii', 'Evergreen with intensely fragrant white flowers.', 'Shrubs', '🌿', 'Apr–May', 'Full Sun / Part Shade', 'Average'),
  plant('Exochorda', 'Parelsnoer', 'Exochorda × macrantha', 'Pearl-white flowers cover the plant completely in spring.', 'Shrubs', '🌸', 'Apr–May', 'Full Sun', 'Average'),
  plant('Rosemary', 'Rozemarijn', 'Salvia rosmarinus', 'Aromatic evergreen herb with blue flowers. Culinary and ornamental.', 'Shrubs', '🌿', 'Apr–Jun', 'Full Sun', 'Low'),
  plant('Lavender Cotton', 'Heiligenbloem', 'Santolina chamaecyparissus', 'Silvery aromatic evergreen with yellow button flowers.', 'Shrubs', '🌿', 'Jul', 'Full Sun', 'Low'),
  plant('Cistus', 'Zonneroosje', 'Cistus × purpureus', 'Papery crinkled flowers. Aromatic evergreen for hot dry spots.', 'Shrubs', '🌸', 'Jun–Jul', 'Full Sun', 'Low'),
  plant('Ceanothus', 'Californische sering', 'Ceanothus thyrsiflorus', 'Clusters of vivid blue flowers. Fast-growing evergreen.', 'Shrubs', '🌸', 'May–Jun', 'Full Sun', 'Average'),
  plant('Leucothoe', 'Leucothoe', 'Leucothoe fontanesiana', 'Arching stems with colorful evergreen foliage. Shade lover.', 'Shrubs', '🌿', 'May', 'Shade', 'Average'),
  plant('Lilac', 'Sering', 'Syringa vulgaris', 'Iconic fragrant panicles in purple, pink, or white.', 'Shrubs', '🌸', 'Apr–May', 'Full Sun', 'Average'),

  // ── Groundcovers ──
  plant('Vinca', 'Maagdenpalm', 'Vinca minor', 'Evergreen trailing stems with blue-purple flowers in spring.', 'Groundcovers', '🌿', 'Mar–May', 'Shade / Part Shade', 'Low'),
  plant('Pachysandra', 'Schaduwgroen', 'Pachysandra terminalis', 'Dense evergreen mat for dry shade. White flowers in spring.', 'Groundcovers', '🌿', 'Apr–May', 'Shade', 'Low'),
  plant('Ajuga', 'Zenegroen', 'Ajuga reptans', 'Carpet of bronze-purple leaves with blue flower spikes.', 'Groundcovers', '🌿', 'Apr–Jun', 'Part Shade', 'Average'),
  plant('Lamium', 'Dovenetel', 'Lamium maculatum', 'Silver-marked leaves with pink or white flowers. Spreads fast.', 'Groundcovers', '🌿', 'Apr–Jun', 'Shade', 'Average'),
  plant('Epimedium', 'Elfenbloem', 'Epimedium × rubrum', 'Heart-shaped leaves, tiny flowers. Tough dry shade plant.', 'Groundcovers', '🌿', 'Apr–May', 'Shade', 'Low'),
  plant('Ivy', 'Klimop', 'Hedera helix', 'Classic evergreen creeper for ground cover or climbing.', 'Groundcovers', '🌿', 'Sep–Oct', 'Shade', 'Low'),
  plant('Cotoneaster', 'Dwergmispel', 'Cotoneaster horizontalis', 'Herringbone branches with red berries. Ground-hugging.', 'Groundcovers', '🌿', 'May', 'Full Sun', 'Low'),
  plant('Creeping Juniper', 'Liggende jeneverbes', 'Juniperus horizontalis', 'Flat spreading evergreen conifer. Blue-green foliage.', 'Groundcovers', '🌿', 'N/A', 'Full Sun', 'Low'),
  plant('Liriope', 'Lirio', 'Liriope muscari', 'Grass-like evergreen with purple flower spikes.', 'Groundcovers', '🌿', 'Aug–Oct', 'Part Shade', 'Low'),
  plant('Ophiopogon', 'Slangenbaardgras', 'Ophiopogon planiscapus', 'Black-leaved grass-like plant. Dramatic accent.', 'Groundcovers', '🌿', 'Jun–Aug', 'Part Shade', 'Average'),
  plant('Wild Strawberry', 'Bosaardbei', 'Fragaria vesca', 'Delicate white flowers, then tiny sweet strawberries.', 'Groundcovers', '🍓', 'May–Jun', 'Part Shade', 'Average'),
  plant('Phlox (Creeping)', 'Kruipende vlambloem', 'Phlox subulata', 'Creates a carpet of starry flowers in spring.', 'Groundcovers', '🌸', 'Apr–May', 'Full Sun', 'Low'),
  plant('Alchemilla', 'Vrouwenmantel', 'Alchemilla mollis', 'Downy scalloped leaves and frothy lime-yellow flowers.', 'Groundcovers', '🌿', 'Jun–Jul', 'Part Shade', 'Average'),
  plant('Persicaria (Low)', 'Lage duizendknoop', 'Persicaria affinis', 'Low creeping mat with pink-red spikes. Long season.', 'Groundcovers', '🌸', 'Jul–Oct', 'Full Sun', 'Average'),
  plant('Acaena', 'Stekelkopje', 'Acaena microphylla', 'Spreading low carpet with spiky red seed heads.', 'Groundcovers', '🌿', 'Jun–Jul', 'Full Sun', 'Low'),
  plant('Armeria', 'Engels gras', 'Armeria maritima', 'Grass-like clumps topped with bright pink pompoms.', 'Groundcovers', '🌸', 'May–Sep', 'Full Sun', 'Low'),
  plant('Sedum (Creeping)', 'Hemelsleutel', 'Sedum spurium', 'Succulent mat with starry pink or white flowers.', 'Groundcovers', '🌿', 'Jul–Aug', 'Full Sun', 'Low'),
  plant('Thyme', 'Tijm', 'Thymus serpyllum', 'Aromatic herb with tiny pink flowers. Walk-on groundcover.', 'Groundcovers', '🌿', 'Jun–Aug', 'Full Sun', 'Low'),
  plant('Chamomile', 'Kamille', 'Chamaemelum nobile', 'Feathery aromatic foliage. White daisy flowers. Walk-on.', 'Groundcovers', '🌼', 'Jun–Aug', 'Full Sun', 'Low'),
  plant('Euonymus (Creeping)', 'Kardinaalsmuts', 'Euonymus fortunei', 'Evergreen variegated groundcover. Very tough and versatile.', 'Groundcovers', '🌿', 'May', 'Full Sun / Shade', 'Low'),

  // ── Bulbs ──
  plant('Tulip', 'Tulp', 'Tulipa spp.', 'Classic spring bulb in every color imaginable.', 'Bulbs', '🌷', 'Mar–May', 'Full Sun', 'Average'),
  plant('Daffodil', 'Narcis', 'Narcissus spp.', 'Cheerful yellow and white trumpets. Naturalizes freely.', 'Bulbs', '🌼', 'Mar–Apr', 'Full Sun', 'Average'),
  plant('Hyacinth', 'Hyacint', 'Hyacinthus orientalis', 'Intensely fragrant upright spike flowers in many colors.', 'Bulbs', '🌸', 'Mar–Apr', 'Full Sun', 'Average'),
  plant('Crocus', 'Krokus', 'Crocus spp.', 'First color of late winter into spring. Naturalizes in lawns.', 'Bulbs', '🌸', 'Feb–Apr', 'Full Sun', 'Average'),
  plant('Snowdrop', 'Sneeuwklokje', 'Galanthus nivalis', 'First flower of the year. Delicate white pendants.', 'Bulbs', '🌸', 'Jan–Feb', 'Part Shade', 'Average'),
  plant('Ornamental Onion', 'Sierui', 'Allium giganteum', 'Ball of purple-violet tiny flowers on tall stems. Architectural.', 'Bulbs', '🌸', 'May–Jun', 'Full Sun', 'Low'),
  plant('Grape Hyacinth', 'Druifhyacint', 'Muscari armeniacum', 'Cobalt-blue grape clusters. Early spring, naturalizes freely.', 'Bulbs', '🌸', 'Apr', 'Full Sun', 'Average'),
  plant('Fritillary', 'Kievitsbloem', 'Fritillaria meleagris', 'Nodding bell flowers with checkered pattern.', 'Bulbs', '🌸', 'Apr–May', 'Full Sun', 'Average'),
  plant('Scilla', 'Wilde hyacint', 'Scilla siberica', 'Brilliant electric blue bells. Naturalizes under trees.', 'Bulbs', '🌸', 'Mar–Apr', 'Part Shade', 'Average'),
  plant('Leucojum', 'Zomerklokje', 'Leucojum aestivum', 'White nodding bells with green tips. Larger than snowdrop.', 'Bulbs', '🌸', 'Mar–Apr', 'Part Shade', 'High'),
  plant('Camassia', 'Prairiester', 'Camassia leichtlinii', 'Tall spires of star-shaped blue flowers. Meadow effect.', 'Bulbs', '🌸', 'May', 'Full Sun', 'Average'),
  plant('Dahlia', 'Dahlia', 'Dahlia spp.', 'Spectacular dinner plate blooms or pompoms. Wide color range.', 'Bulbs', '🌺', 'Jul–Oct', 'Full Sun', 'Average'),
  plant('Gladiolus', 'Gladiool', 'Gladiolus spp.', 'Tall sword spikes with showy flowers in every color.', 'Bulbs', '🌸', 'Jul–Sep', 'Full Sun', 'Average'),
  plant('Lily', 'Lelie', 'Lilium spp.', 'Elegant trumpet flowers, intensely fragrant Oriental types.', 'Bulbs', '🌸', 'Jun–Aug', 'Full Sun', 'Average'),
  plant('Cyclamen', 'Cyclaam', 'Cyclamen hederifolium', 'Reflexed swept-back petals. Marbled silver foliage.', 'Bulbs', '🌸', 'Sep–Nov', 'Shade', 'Low'),
  plant('Nerine', 'Nerine', 'Nerine bowdenii', 'Spidery pink flowers on bare stems in autumn.', 'Bulbs', '🌸', 'Sep–Oct', 'Full Sun', 'Low'),
  plant('Chionodoxa', 'Sneeuwroem', 'Chionodoxa luciliae', 'Star-shaped blue flowers with white center. Early spring.', 'Bulbs', '🌸', 'Mar', 'Full Sun', 'Average'),

  // ── Climbers ──
  plant('Clematis', 'Bosrank', 'Clematis spp.', 'Hundreds of varieties. Starry to large flowers in all colors.', 'Climbers', '🌸', 'Apr–Oct', 'Full Sun', 'Average'),
  plant('Wisteria', 'Blauweregen', 'Wisteria sinensis', 'Long fragrant racemes in purple, lilac, or white. Vigorous.', 'Climbers', '🌸', 'Apr–May', 'Full Sun', 'Average'),
  plant('Climbing Rose', 'Klimroos', 'Rosa spp.', 'Classic romantic fragrant flowers. Many colors and forms.', 'Climbers', '🌹', 'Jun–Sep', 'Full Sun', 'Average'),
  plant('Honeysuckle', 'Kamperfoelie', 'Lonicera periclymenum', 'Sweetly fragrant tubular flowers. Evening scent attracts moths.', 'Climbers', '🌺', 'Jun–Sep', 'Full Sun / Part Shade', 'Average'),
  plant('Climbing Hydrangea', 'Klimhortensia', 'Hydrangea anomala petiolaris', 'Self-clinging with white lacecap flowers. Ideal for walls.', 'Climbers', '🌸', 'Jun–Jul', 'Part Shade', 'Average'),
  plant('Virginia Creeper', 'Wilde wingerd', 'Parthenocissus quinquefolia', 'Self-clinging foliage turning brilliant scarlet in autumn.', 'Climbers', '🍁', 'Sep–Nov', 'Full Sun / Part Shade', 'Average'),
  plant('Jasmine', 'Jasmijn', 'Jasminum officinale', 'Intensely fragrant white starry flowers all summer.', 'Climbers', '🌸', 'Jun–Sep', 'Full Sun', 'Average'),
  plant('Passionflower', 'Passiebloem', 'Passiflora caerulea', 'Exotic intricate blue-white flowers. Fast growing.', 'Climbers', '🌸', 'Jun–Sep', 'Full Sun', 'Average'),
  plant('Star Jasmine', 'Sterjasmijn', 'Trachelospermum jasminoides', 'Evergreen twiner with intensely fragrant white flowers.', 'Climbers', '🌸', 'Jun–Aug', 'Full Sun', 'Average'),
  plant('Ornamental Vine', 'Druif', 'Vitis vinifera Purpurea', 'Purple foliage, small decorative grapes. Autumn color.', 'Climbers', '🍇', 'Sep–Oct', 'Full Sun', 'Average'),
  plant('Actinidia', 'Actinidia', 'Actinidia kolomikta', 'Leaves splashed pink and white. Small kiwi-like fruit.', 'Climbers', '🌿', 'May–Jun', 'Full Sun', 'Average'),
  plant('Sweet Pea', 'Lathyrus', 'Lathyrus odoratus', 'Delicate fragrant flowers in many colors. Annual climber.', 'Climbers', '🌸', 'Jun–Sep', 'Full Sun', 'Average'),
  plant('Campsis', 'Trompetbloem', 'Campsis radicans', 'Bold orange-red trumpet flowers. Self-clinging. Vigorous.', 'Climbers', '🌺', 'Jul–Sep', 'Full Sun', 'Average'),

  // ── Trees ──
  plant('Serviceberry', 'Krentenboompje', 'Amelanchier lamarckii', 'White spring blossom, edible berries, fiery autumn color.', 'Trees', '🌳', 'Apr', 'Full Sun', 'Average'),
  plant('Silver Birch', 'Zilverberk', 'Betula pendula', 'Graceful tree with white peeling bark. Airy catkin flowers.', 'Trees', '🌳', 'Mar–Apr', 'Full Sun', 'Low'),
  plant('Redbud', 'Judasboom', 'Cercis siliquastrum', 'Bright pink flowers emerge directly from the bark in spring.', 'Trees', '🌸', 'Apr–May', 'Full Sun', 'Low'),
  plant('Flowering Cherry', 'Sierkersenboom', 'Prunus serrulata', 'Spectacular spring blossom display in pink or white.', 'Trees', '🌸', 'Apr', 'Full Sun', 'Average'),
  plant('Crabapple', 'Sierappel', 'Malus spp.', 'Spring blossom followed by decorative fruit. Many varieties.', 'Trees', '🌸', 'Apr–May', 'Full Sun', 'Average'),
  plant('Rowan', 'Lijsterbes', 'Sorbus aucuparia', 'White flowers then clusters of red berries. Bird-attracting.', 'Trees', '🌳', 'May', 'Full Sun', 'Average'),
  plant('Magnolia', 'Magnolia', 'Magnolia soulangeana', 'Giant cup flowers in pink-white before leaves emerge.', 'Trees', '🌸', 'Mar–Apr', 'Full Sun / Part Shade', 'Average'),
  plant('Sweet Gum', 'Liquidambar', 'Liquidambar styraciflua', 'Star-shaped leaves turning vivid red-orange-yellow in autumn.', 'Trees', '🍁', 'Oct', 'Full Sun', 'Average'),
  plant('Gleditsia', 'Valse christusdoorn', 'Gleditsia triacanthos', 'Feathery golden-green foliage. Elegant and light.', 'Trees', '🌳', 'Summer', 'Full Sun', 'Low'),
  plant('Hawthorn', 'Meidoorn', 'Crataegus laevigata', 'Fragrant white or pink blossom, then red haws. Wildlife tree.', 'Trees', '🌳', 'May', 'Full Sun', 'Low'),
  plant('Flowering Pear', 'Sierpeer', 'Pyrus calleryana', 'White blossom in spring, glossy dark foliage, autumn color.', 'Trees', '🌸', 'Apr', 'Full Sun', 'Low'),
  plant('Styrax', 'Storaxboom', 'Styrax japonicus', 'White bell flowers hanging under the canopy. Fragrant.', 'Trees', '🌸', 'Jun', 'Full Sun / Part Shade', 'Average'),
  plant('Cercidiphyllum', 'Katsuranboom', 'Cercidiphyllum japonicum', 'Heart-shaped leaves, burnt caramel autumn scent.', 'Trees', '🍁', 'Oct', 'Full Sun / Part Shade', 'Average'),
  plant('Hazel', 'Hazelaar', 'Corylus avellana', 'Catkins in late winter, edible hazelnuts in autumn.', 'Trees', '🌳', 'Feb', 'Full Sun / Part Shade', 'Average'),
  plant('Sea Buckthorn', 'Duindoorn', 'Hippophae rhamnoides', 'Silvery foliage, vivid orange berries. Wind tolerant.', 'Trees', '🌳', 'Aug (fruit)', 'Full Sun', 'Low'),
];

export function getPlantInstruction(plant: PlantCatalogItem): string {
  return `Add a ${plant.name} (${plant.latinName}) to the garden in a suitable location. Keep everything else exactly as it is.`;
}
